{
 "title": "http monitor",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(backend_model_http_request_duration_seconds_count{handler!=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration Count by Handler",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (backend_model_http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration by Endpoint",
   "type": "bargauge",
   "description": "Average request time by endpoint",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (backend_model_http_request_duration_seconds_sum{handler!=\"none\"} / backend_model_http_requests_total{handler!=\"none\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Total uploaded data",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backend_model_payload_bytes_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests by method",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (backend_model_http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Browsers",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(browser) (backend_model_user_agent_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time by operation",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_model_processing_seconds_sum/backend_model_processing_seconds_count",
     "legendFormat": "{{time}}"
    }
   ]
  }
 ]
}