name: Build Frontend

on: 
  workflow_dispatch:
  workflow_call:

jobs:

  dockerize_frontend:
    runs-on: self-hosted
    
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Canister.io
        uses: docker/login-action@v2
        with:
          registry: cloud.canister.io:5000
          username: ${{ secrets.CANISTER_USERNAME }}
          password: ${{ secrets.CANISTER_PASSWORD }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/app/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cloud.canister.io:5000/aaurso/frontend:latest
            valeriolong/frontend:latest
