name: Quality Check Full

on:
  pull_request:
    types:
    - ready_for_review
    branches:
    - main
    - dev
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: 3.10.9


jobs:

  test_marked:
    name: Test
    runs-on: self-hosted
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3


    - name: Setup Python MacOS
      if: ${{ startsWith(runner.os, 'macOS') }} &&  $ {{ runner.arch == 'ARM64' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Python
      if: ${{ runner.os }} != 'macOS'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: pip cache
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testing with pytest
      run: |
        pytest -m "not require_model"
