name: Quality Check Fast

on:
  # push:
  #  branches:
  #  - main
  #  - dev
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: 3.10.9

jobs:

  lint:
    name: "Static analysis"
    runs-on: self-hosted
    steps:

    - name: "Checkout Repository"
      uses: actions/checkout@v3

    - name: Setup Python MacOS
      if: ${{ startsWith(runner.os, 'macOS') && runner.arch == 'ARM64' }}
      uses: actions/setup-python@v4
      with:
        architecture: 'ARM64'
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Python
      if: ${{ !startsWith(runner.os, 'macOS') }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Linting with pylint
      run: |
        pylint pylint --fail-under=8 $(git ls-files '*.py')

  test_unmarked:
    name: Test unmarked
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python MacOS
      if: ${{ startsWith(runner.os, 'macOS') && runner.arch == 'ARM64' }}
      uses: actions/setup-python@v4
      with:
        architecture: 'ARM64'
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Python
      if: ${{ !startsWith(runner.os, 'macOS') }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testing with pytest
      run: |
        pytest -m "not require_data and not require_scans and not require_model"
