name: Virtual Environment Setup

on: 
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: 3.10.9

jobs:

  create-virtualenv:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: pip cache
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }} 

    - name: Setup venv (no cache hit)
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
